web:
  build: ./app
  ports:
    - "5000:5000"
  # don't change the mount _destination_ of modules (syntax: "source:destination")
  volumes:
    # - ./app:/app # only on dev
    # the shared data folder
    - /Users/valentinarho/Downloads/om-integration/data:/data
    # the logs folder
    - /Users/valentinarho/Downloads/om-integration/logs:/logs
    # - /Users/valentinarho/Downloads/om-integration/nltk_data:/usr/share/nltk_data
  links:
    - db
db:
  image: mongo:3
  # uncomment to map the mongodb port to the external machine port
  #ports:
  #  - "27017:27017/tcp"
